version: '3.8'

services:
  jekyll:
    build: .
    ports:
      - "2255:2255"
      - "35729:35729" # Port for livereload
    volumes:
      - .:/srv/jekyll
    command: bundle exec jekyll serve --host 0.0.0.0 --port 2255 --force_polling --livereload --baseurl "" --trace
    environment:
      - JEKYLL_ENV=development
